### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by thunder-007** [FLAK-ZOSO/FLAK-ZOSO.github.io#1]
Discord link isn't working

**Comment by FLAK-ZOSO** [comment]
@thunder-007 you are one of thos ones from StackOverflow, right? Anyway my discord name is FLAK_FLAK#3241.

For this kind of communication is better not to open an issue, since they are not supposed to work this way.

**Comment by FLAK-ZOSO** [comment]
@thunder-007 r u there?

**Comment by thunder-007** [comment]
> @thunder-007 r u there?

Yeah hello

**Comment by FLAK-ZOSO** [comment]
What were you asking above?

**Comment by FLAK-ZOSO** [comment]
Oh, ok, now I understand. The link to discord in the sidebar has expired? In reality the link takes you to a DM with me only if you already have one, otherwise it doesn't work. I haven't found any other option to do it. Anyway if you need me contact me at `FLAK_FLAK#3241`
